### ISSUE TITLE
SYNTAX update in SW_Obs_QC_v2

### ISSUE THREAD

**Issue by NicWayand** [klapo/moq#2]
%   FLAGS = SW_Obs_QC(DATstr)
%   FLAGS = SW_Obs_QC(DATstr,FIG_FLAG)

should be

%   FLAGS = SW_Obs_QC_v2(DATstr)
%   FLAGS = SW_Obs_QC_v2(DATstr,FIG_FLAG)

**Comment by klapo** [comment]
Fixed
